### ISSUE TITLE
Allow the creation of resources with a predefined ids

### ISSUE THREAD

**Issue by mr-beerkiss** [photobox/cruddy-simple#5]
We have a situation at Photobox where, because of the lack of any kind of admin UI, we end up having to send full blobs of JSON (including ids) to the services to create and update data.  This is because all data is crafted by hand. It is much easier to use human readable ids, because this is less cognitive load for someone crafting the data.

However, cruddy-simple allows no way of allowing one to create entries with a predefined ID. Thus, we are in an awkward situation where we cannot use the API as it stands to create the data that we need to power our applications.

I propose 3 solutions to this problem.

1.  Allow PUT to create resources if they don't exist (idempotent)
1.  Allow POST to create resources if they don't exist (also idempotent in a way but slightly confusing given the way POST behaves if you don't supply a resource id)
1.  Modify Dynamo DB to maintain it's own unique for each entry created, but maintain any hand-crafted id contained in the data as is.

I'm personally for the first option since it can be viewed as a purely idempotent operation and will not require any significant rewriting of the code or restructuring of the data.  In the long run, particularly given the need to eventually apply the idea of data maturity to our services, option 3 is a solid contender but requires wide reaching changes across DynamoDB, data and the services themselves.

Before I went ahead and made a PR I thought it would be best to have an open discussion to go over my proposal and possibly surface some new options.

**Comment by ChristopherTD** [comment]
If we adopt option 1, would an update be a DELETE followed by a POST? Or do updates work OK at the moment, it's just creation of resources with an arbitrary id we need to fix?

**Comment by mr-beerkiss** [comment]
it wouldn't be a DELETE, it would just perform a full update if the resource already exists, or it would create it if it didn't.  This is actually the way the AWS SDK DynamoDB update method works so it isn't a particularly novel concept.

**Comment by CrackPT** [comment]
I don't know much about the implementation that we are talking about, but I would have a look at this discussion (the two first comments are excellent and help you decide on which approach to take).

https://stackoverflow.com/questions/630453/put-vs-post-in-rest

From what I can see, it really depends on how you want the application to behave. 
If you specify the id of the entity in the URL, then you can use PUT to create/update because the result of that call will always result in a single new/existing resource. Otherwise, you should use POST and let the application return you the ID that you expect (and every single call should result in a new entity).

If your suggestion also considers specifying the id in the URL and allow PUT to create/update a new entity, I am fine with that, and I think that we are following the best practices.

**Comment by mr-beerkiss** [comment]
At @CrackPT I read that link this morning and it inspired me to put this discussion together

**Comment by mr-beerkiss** [comment]
So after speaking with @mattphillips it was decided the best route is to build the ability for PUT to create, but this will be disabled by default (for all our non-Photobox use cases).  You'll be able enable and disable this feature by toggling a flag in the configuration.  PR to follow shortly

**Comment by mr-beerkiss** [comment]
https://github.com/photobox/cruddy-simple/pull/6
